import = [
    "~/dotfiles/alacritty/themes/themes/citylights.toml"
]

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"] 

[window]
# Set opacity to full for now (default)
opacity = 1.00
decorations = "full"
padding.x = 3
padding.y = 3

[font]
normal = {family = "JetBrains Mono", style = "Regular"}
size = 15.0
