import = [
    "~/dotfiles/alacritty/themes/themes/everforest_dark.toml"
]

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"] 

[window]
# Set opacity to full for now (default)
opacity = 1.00
decorations = "full"
padding.x = 3
padding.y = 3

[font]
normal = {family = "JetBrainsMono Nerd Font Mono", style = "Regular"}
bold = {family = "JetBrainsMono Nerd Font Mono", style = "Bold"}
italic = {family = "JetBrainsMono Nerd Font Mono", style = "Italic"}
bold_italic = {family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic"}
size = 15.0
