import = [
    "~/dotfiles/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
]
  
# [colors.primary]
# background = '0x222222'
# foreground = '0xAAAAAA'

[window]
opacity = 0.98
decorations = "full"

[font]
size = 14.0
