# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true 

format = '''
$directory$git_branch [➜](bold green) 
'''

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[gcloud]
disabled = true

[conda]
ignore_base = true

[directory]
truncate_to_repo = true
truncation_length = 3

[git_branch]
format = 'git:[($branch)]($style)'
