set -g default-terminal "screen-256color"

# ==================== Meta Configuration ==================

# Sets tmux leader to ctrl-space
unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

# Relad tmux conf using <leader>r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# ==================== Navigation ==================

# <leader>Space - Jump to the next window 
bind Space next-window

# <leader>j - Create a new session with prompt for name
unbind j
bind j command-prompt -p "New Session:" "new-session -A -s '%%'"

# <leader>< or > - Swap window locations
bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1

# <leader>c - new window in the same session
bind c new-window

# <leader>x - kill current window
bind x kill-window

# ==================== Status Bar ==================

# Put the status bar at the top
set-option -g status-position top
set -g status-bg black
set -g status-fg white

# Adds padding at the bottom of the status bar
set -Fg 'status-format[1]' '#{status-format[0]}'
set -g 'status-format[1]' ''
set -g status 2

# Updates how the window tabs are labeled in the status bar
set-window-option -g window-status-format ' #I: #[fg=green]#{pane_current_command}#[default]'
set-window-option -g window-status-current-format '#[fg=green,bold] ** #I: #{pane_current_command} **#[default]'
set-window-option -g window-status-separator ' |'
set-option -g status-left-length 50
set -g status-interval 1

# Sets config for left side of the status bar
set -g status-left '[#{session_name}]'

# Sets configs for the right side of the status bar
set-option -g status-right-length 50
set -g status-right '#(basename #{pane_current_path}) | %Y-%m-%d %H:%M'

